### ISSUE TITLE
Armar clases para sitio web

### ISSUE THREAD

**Issue by ivanvgav** [ivanvgav/logica-2024#1]
### Tasks:
- [x] Generar `git` para la web
- [x] Armar clase unidad 1
- [x] Armar clase unidad 2
- [x] Armar clase unidad 3
- [x] Armar clase unidad 4
- [x] Armar clase unidad 5
- [x] Armar clase unidad 6
- [x] Armar clase unidad 7
- [x] Configurar tema de las imágenes
- [x] Agregar referencias bibliográficas
- [x] Subir a la web
